/**
 * OpenModel Selector - Dataset
 * Integrates:
 * 1. Day 16 Selection Methodology (Ivan Usto / llm-zhtw-agent-exam)
 * 2. Arena.ai Coding Leaderboard (LMSYS Chatbot Arena Code Elo & Benchmarks)
 * 3. CanIRun.ai Hardware Profiles & VRAM/KV Cache footprint formulas
 *
 * 資料原則：每個數字都要有來源（見各模型的 sources）；查不到就是 null，介面顯示「無資料」。
 * kvPerTokKB 為 BF16、只計全注意力層，依 HF config.json 推導（另有註明者除外）。
 * arenaCodeElo／arenaWebdevElo 由 scripts/sync_leaderboard.py 每週從 LMArena 官方資料集更新。
 */

const DATA_ASOF = {
  arena: 'text-coding 2026-09-13 / webdev 2026-09-11',
  specs: '2026-09-22'
};

const HARDWARE_PROFILES = [
  // 頻寬以原廠規格頁為準（2026-09-22 核對）；GeForce 原廠頁不列 GB/s，取自常見規格資料庫
  // AI Superchips & Workstations (Grace Blackwell & Grace Hopper)
  { id: 'nvidia-gb10', name: 'NVIDIA GB10 / DGX Spark (128GB Unified)', type: 'superchip', vramGB: 128, unified: true, memBandwidthGBs: 273, description: '20 核 Grace CPU + Blackwell GPU，128GB LPDDR5X 統一記憶體（256-bit、273 GB/s），1 PFLOPS FP4；容量大但頻寬是瓶頸' },
  { id: 'dual-gb10', name: '雙機 NVIDIA GB10 / DGX Spark (2x128GB，CX7 直連)', type: 'superchip', vramGB: 256, unified: true, memBandwidthGBs: 546, description: '兩台 GB10 以 ConnectX-7 直連做張量並行（Day 27）；頻寬為兩台加總，實際受跨機通訊影響。DeepSeek-V4/V4.1-Flash 的本機實測平台' },
  { id: 'nvidia-gb200', name: 'NVIDIA GB200 Superchip (372GB HBM3e)', type: 'superchip', vramGB: 372, unified: true, memBandwidthGBs: 16000, description: '1 顆 Grace + 2 顆 B200，372GB HBM3e（16 TB/s）另有最多 480GB LPDDR5X；資料中心等級' },
  { id: 'nvidia-gh200', name: 'NVIDIA GH200 (144GB HBM3e)', type: 'superchip', vramGB: 144, unified: true, memBandwidthGBs: 4000, description: '企業級超級晶片，144GB HBM3e 加 480GB LPDDR5X；頻寬取 96GB HBM3 版的 4 TB/s 保守估計（原廠未單列 144GB 版單晶片數字）' },
  { id: 'nvidia-h200-141', name: 'NVIDIA H200 (141GB HBM3e)', type: 'enterprise', vramGB: 141, unified: false, memBandwidthGBs: 4800, description: '141GB HBM3e、4.8 TB/s，單卡可放 70B FP16 或 120B 級 MoE 8-bit' },

  // Apple Silicon Unified Memory
  { id: 'mac-16', name: 'Apple M5 (16GB Unified)', type: 'apple', vramGB: 16, unified: true, memBandwidthGBs: 153, description: '入門級統一記憶體（M5 153 GB/s；M4 為 120），適合 7B~9B Q8 或 14B Q4' },
  { id: 'mac-24', name: 'Apple M5 (24GB Unified)', type: 'apple', vramGB: 24, unified: true, memBandwidthGBs: 153, description: '24G 等級，可跑 27B/32B Q4_K_M，但頻寬低、decode 慢' },
  { id: 'mac-m6-32', name: 'Apple M6 (32GB Unified)', type: 'apple', vramGB: 32, unified: true, memBandwidthGBs: 170, description: '2026-09 上市的 M6（Mac mini），最高 32GB、170 GB/s' },
  { id: 'mac-36', name: 'Apple M5 Max 32C GPU (36GB Unified)', type: 'apple', vramGB: 36, unified: true, memBandwidthGBs: 460, description: '36GB 只出在 Max 的低階版（M5 Max 460 GB/s；M4 Max 為 410）' },
  { id: 'mac-m5pro-64', name: 'Apple M5 Pro (64GB Unified)', type: 'apple', vramGB: 64, unified: true, memBandwidthGBs: 307, description: 'M5 Pro 最高 64GB、307 GB/s；容量夠放 70B Q4，但頻寬只有 Max 的一半' },
  { id: 'mac-48', name: 'Apple M5 Max 40C GPU (48GB Unified)', type: 'apple', vramGB: 48, unified: true, memBandwidthGBs: 614, description: '中高階工作站（M5 Max 614 GB/s；M4 Max 為 546），可順暢運行 32B 8-bit' },
  { id: 'mac-64', name: 'Apple M5 Max 40C GPU (64GB Unified)', type: 'apple', vramGB: 64, unified: true, memBandwidthGBs: 614, description: '70B 密集模型 Q4/Q5 舒適區，35B 級 MoE 8-bit' },
  { id: 'mac-96', name: 'Apple M3 Ultra (96GB Unified)', type: 'apple', vramGB: 96, unified: true, memBandwidthGBs: 819, description: 'M3 Ultra 起跳容量，819 GB/s；gpt-oss-120b MXFP4 可放' },
  { id: 'mac-128', name: 'Apple M5 Max / M4 Max (128GB Unified)', type: 'apple', vramGB: 128, unified: true, memBandwidthGBs: 614, description: '與 GB10 同容量級（M5 Max 614 GB/s；M4 Max 546），可跑 Ornith 1.5 BF16 或 120B 級 MoE' },
  { id: 'mac-192', name: 'Apple M2 Ultra (192GB Unified)', type: 'apple', vramGB: 192, unified: true, memBandwidthGBs: 800, description: '舊款 Mac Studio 最大容量，800 GB/s' },
  { id: 'mac-256', name: 'Apple M3 Ultra (256GB Unified)', type: 'apple', vramGB: 256, unified: true, memBandwidthGBs: 819, description: 'M3 Ultra 在 2026-03 後的最高容量；DeepSeek-V4-Flash 4-bit 級可放' },
  { id: 'mac-512', name: 'Apple Mac Studio M5 Ultra (512GB Unified)', type: 'apple', vramGB: 512, unified: true, memBandwidthGBs: 1200, description: 'M5 Ultra 1.2 TB/s，512GB 版 2026 年 10 月下旬出貨；可放 V4.1-Flash 2~3 bit 或 V4-Flash 8-bit' },

  // NVIDIA GeForce RTX Series (RTX 30 / 40 / 50 Series)
  { id: 'rtx-5090-32', name: 'NVIDIA RTX 5090 (32GB GDDR7)', type: 'nvidia', vramGB: 32, unified: false, memBandwidthGBs: 1792, description: 'Blackwell 單卡之王，32B 級 8-bit 或 27B/31B BF16 邊緣' },
  { id: 'rtx-5080-16', name: 'NVIDIA RTX 5080 (16GB GDDR7)', type: 'nvidia', vramGB: 16, unified: false, memBandwidthGBs: 960, description: 'Blackwell 256-bit，960 GB/s' },
  { id: 'rtx-5070-12', name: 'NVIDIA RTX 5070 (12GB GDDR7)', type: 'nvidia', vramGB: 12, unified: false, memBandwidthGBs: 672, description: '12G 顯卡，高速 7B/8B/14B 本地推論' },
  { id: 'rtx-5060ti-16', name: 'NVIDIA RTX 5060 Ti (16GB GDDR7)', type: 'nvidia', vramGB: 16, unified: false, memBandwidthGBs: 448, description: '高 CP 值 16G，可跑 24B Q4 或 20B 級 MoE' },
  { id: 'rtx-4090-24', name: 'NVIDIA RTX 4090 / 3090 (24GB VRAM)', type: 'nvidia', vramGB: 24, unified: false, memBandwidthGBs: 1008, description: '24G 旗艦單卡（4090 1008 GB/s；3090 為 936），27B~35B Q4_K_M 加 KV' },
  { id: 'rtx-4080-16', name: 'NVIDIA RTX 4080 / Super (16GB VRAM)', type: 'nvidia', vramGB: 16, unified: false, memBandwidthGBs: 736, description: '高速 16GB（Super 736 GB/s；原版 717），極佳的 7B/8B/14B 生產速度' },
  { id: 'rtx-4070tis-16', name: 'NVIDIA RTX 4070 Ti Super (16GB VRAM)', type: 'nvidia', vramGB: 16, unified: false, memBandwidthGBs: 672, description: '256-bit 16GB，適合 14B 8-bit 或 24B Q4' },
  { id: 'rtx-4070-12', name: 'NVIDIA RTX 4070 / Super (12GB VRAM)', type: 'nvidia', vramGB: 12, unified: false, memBandwidthGBs: 504, description: '12G，適合 7B/8B 8-bit 高速推論' },
  { id: 'rtx-4060ti-16', name: 'NVIDIA RTX 4060 Ti (16GB VRAM)', type: 'nvidia', vramGB: 16, unified: false, memBandwidthGBs: 288, description: '經典 16G 顯存，可跑 7B FP16 或 14B Q8' },
  { id: 'rtx-4060-8', name: 'NVIDIA RTX 4060 (8GB VRAM)', type: 'nvidia', vramGB: 8, unified: false, memBandwidthGBs: 272, description: '入門顯卡，適合 7B Q4_K_M / 3B FP16' },
  { id: 'rtx-3060-12', name: 'NVIDIA RTX 3060 (12GB VRAM)', type: 'nvidia', vramGB: 12, unified: false, memBandwidthGBs: 360, description: '平民裝機神器，適合 7B/8B Q8 或 14B Q4' },
  { id: 'dual-4090-48', name: '雙卡 2x RTX 4090/3090 (48GB VRAM)', type: 'nvidia', vramGB: 48, unified: false, memBandwidthGBs: 2016, description: '雙卡 48G，70B Q4_K_M 或 32B 級 8-bit；頻寬為兩卡加總，實際受張量並行效率影響' },
  { id: 'dual-5090-64', name: '雙卡 2x RTX 5090 (64GB VRAM)', type: 'nvidia', vramGB: 64, unified: false, memBandwidthGBs: 3584, description: '70B 8-bit 邊緣 / 120B MoE Q4 雙卡直推' },

  // AMD & Intel
  { id: 'amd-ryzen-ai-max-395', name: 'AMD Ryzen AI Max+ 395 (128GB，GPU 可配 96GB)', type: 'amd', vramGB: 96, unified: true, memBandwidthGBs: 256, description: 'Strix Halo，128GB LPDDR5X-8000，最多 96GB 劃給 GPU，256 GB/s；與 GB10 同級容量的 x86 方案' },
  { id: 'amd-rx7900xtx', name: 'AMD Radeon RX 7900 XTX (24GB VRAM)', type: 'amd', vramGB: 24, unified: false, memBandwidthGBs: 960, description: 'ROCm / Vulkan 支援，24GB 大顯存高 CP 值選擇' },
  { id: 'amd-rx7900xt', name: 'AMD Radeon RX 7900 XT (20GB VRAM)', type: 'amd', vramGB: 20, unified: false, memBandwidthGBs: 800, description: '20GB 大顯存，支援 14B 8-bit 或 24B Q4_K_M' },
  { id: 'amd-rx7800xt', name: 'AMD Radeon RX 7800 XT (16GB VRAM)', type: 'amd', vramGB: 16, unified: false, memBandwidthGBs: 624, description: '16GB 顯存，性價比極佳的 8B/14B 推論卡' },
  { id: 'amd-rx9070xt', name: 'AMD Radeon RX 9070 XT (16GB VRAM)', type: 'amd', vramGB: 16, unified: false, memBandwidthGBs: 640, description: 'RDNA 4，256-bit 16GB、640 GB/s' },
  { id: 'intel-arc-b580', name: 'Intel Arc B580 (12GB VRAM)', type: 'intel', vramGB: 12, unified: false, memBandwidthGBs: 456, description: 'Battlemage 新架構，平價 12G 本地 AI 推論' },
  { id: 'intel-arc-a770', name: 'Intel Arc A770 (16GB VRAM)', type: 'intel', vramGB: 16, unified: false, memBandwidthGBs: 560, description: 'IPEX-LLM / llama.cpp Vulkan 支援，平價 16G 顯卡' },

  // Enterprise & Workstation
  { id: 'rtx-pro-6000-96', name: 'NVIDIA RTX PRO 6000 Blackwell (96GB GDDR7)', type: 'enterprise', vramGB: 96, unified: false, memBandwidthGBs: 1792, description: '工作站單卡 96GB ECC、1.8 TB/s；gpt-oss-120b 單卡全放' },
  { id: 'rtx-6000-ada', name: 'NVIDIA RTX 6000 Ada (48GB VRAM)', type: 'enterprise', vramGB: 48, unified: false, memBandwidthGBs: 960, description: '專業工作站單卡 48G ECC 顯存' },
  { id: 'nvidia-h100-80', name: 'NVIDIA H100 SXM (80GB HBM3)', type: 'enterprise', vramGB: 80, unified: false, memBandwidthGBs: 3350, description: '資料中心旗艦，3.35 TB/s，70B 8-bit 企業級推論' },
  { id: 'nvidia-a100-80', name: 'NVIDIA A100 SXM (80GB HBM2e)', type: 'enterprise', vramGB: 80, unified: false, memBandwidthGBs: 2039, description: '資料中心旗艦，80G、2 TB/s 企業級推論標準' },

  // CPU System Memory
  { id: 'cpu-32', name: 'PC / 伺服器 CPU (32GB RAM)', type: 'cpu', vramGB: 32, unified: true, memBandwidthGBs: 60, description: '純 CPU 推論，適合 7B~14B Q4_K_M 或 3B 啟用的 MoE' },
  { id: 'cpu-64', name: 'PC / 伺服器 CPU (64GB RAM)', type: 'cpu', vramGB: 64, unified: true, memBandwidthGBs: 80, description: '純 CPU 推論，小啟用量 MoE（如 35B-A3B）最划算' },
  { id: 'cpu-128', name: 'PC / 伺服器 CPU (128GB DDR5 RAM)', type: 'cpu', vramGB: 128, unified: true, memBandwidthGBs: 100, description: 'Day 16 探討的大記憶體共存方案，可跑大型 MoE' },
  { id: 'cpu-256', name: '伺服器 CPU (256GB RAM)', type: 'cpu', vramGB: 256, unified: true, memBandwidthGBs: 120, description: '超大記憶體伺服器，支援百 B 級 MoE 量化檔 CPU 推論' }
];

const MODELS_DATABASE = [
  {
    id: 'qwen25-coder-32b',
    name: 'Qwen2.5-Coder-32B-Instruct',
    family: 'Qwen',
    paramsTotal: 32.8,
    paramsActive: 32.8,
    architecture: 'Dense',
    license: 'Apache 2.0',
    commercialAllowed: true,
    contextWindow: 131072,
    nativeContext: 32768,
    arenaKey: 'qwen2.5-coder-32b-instruct',
    arenaWebdevKey: null,
    arenaCodeElo: 1342.3,
    arenaWebdevElo: null,
    humanEval: 92.7,
    sweBench: null,
    liveCodeBench: null,
    tcGrade: 'A',
    tcQuantMinBit: '8-bit',
    tcQuantNote: '繁中表現穩定；4-bit 量化的繁中劣化約為英文的 1.6~2 倍（Day 12 實測通則），建議 Q8_0 或 imatrix 系。',
    jsonDisciplineScore: null,
    jsonNote: '未在繁中 Agent 考卷上實測。',
    kvPerTokKB: 256,
    speedPrefillScore: 95,
    speedDecodeRating: '未實測（密集 32B，受頻寬限制）',
    workloadFit: { prefill: 5, decode: 3, agent: 4.5 },
    engineSupport: 'Production Merged',
    engineNotes: 'vLLM、llama.cpp、Ollama、SGLang、MLX 皆已正式支援，生態成熟。',
    storageAdvise: '常駐主力放本機 NVMe；Q4_K_M 約 20 GB。',
    examScore: null,
    isDay16Featured: true,
    day16Role: '上一代密集 32B 程式碼標竿：Prefill 效率高，適合長文 RAG 與 Repo 分析',
    editorial: 'tcGrade、workloadFit、speedPrefillScore 為 Day 16 作者評分',
    quantProfiles: {
      BF16: { sizeGB: 65.5, bpw: 16.0, recSpeedGpu: '需 48 GB 以上' },
      Q8_0: { sizeGB: 34.8, bpw: 8.5, recSpeedGpu: '32 GB 以上（RTX 5090 邊緣）' },
      Q5_K_M: { sizeGB: 23.3, bpw: 5.7, recSpeedGpu: '24 GB 顯卡剛好' },
      Q4_K_M: { sizeGB: 19.9, bpw: 4.9, recSpeedGpu: '24 GB 顯卡留 KV 餘裕' }
    },
    sources: {
      arena: 'https://arena.ai/leaderboard/text/coding',
      specs: 'https://huggingface.co/Qwen/Qwen2.5-Coder-32B-Instruct',
      benchmarks: 'https://arxiv.org/abs/2409.12186（Table 16，HumanEval）',
      quant: 'https://huggingface.co/bartowski/Qwen2.5-Coder-32B-Instruct-GGUF'
    }
  },
  {
    id: 'deepseek-r1-moe',
    name: 'DeepSeek-R1 (MoE 671B)',
    family: 'DeepSeek',
    paramsTotal: 671.0,
    paramsActive: 37.0,
    architecture: 'MoE',
    license: 'MIT',
    commercialAllowed: true,
    contextWindow: 163840,
    nativeContext: 163840,
    arenaKey: 'deepseek-r1',
    arenaWebdevKey: null,
    arenaCodeElo: 1444.5,
    arenaWebdevElo: null,
    humanEval: null,
    sweBench: 49.2,
    liveCodeBench: 65.9,
    tcGrade: 'S',
    tcQuantMinBit: 'Q4_K_M (imatrix) / FP8',
    tcQuantNote: '思維鏈推理型；已被 V3.2 與 V4 系列取代，保留作為對照。',
    jsonDisciplineScore: null,
    jsonNote: '長推理會消耗大量 decode token；未在繁中 Agent 考卷上實測。',
    kvPerTokKB: 68.6,
    speedPrefillScore: 80,
    speedDecodeRating: '未實測（啟用 37B）',
    workloadFit: { prefill: 4, decode: 5, agent: 5 },
    engineSupport: 'Production Merged',
    engineNotes: 'vLLM、SGLang、llama.cpp、KTransformers 完整支援 MLA/MoE。',
    storageAdvise: 'Q4_K_M 約 404 GB，需高速 NVMe。',
    examScore: null,
    isDay16Featured: false,
    day16Role: '上一代開源推理代表：MLA 讓 KV 成本遠低於同級 GQA',
    editorial: 'tcGrade、workloadFit、speedPrefillScore 為 Day 16 作者評分',
    quantProfiles: {
      BF16: { sizeGB: 1342.3, bpw: 16.0, recSpeedGpu: '多卡資料中心' },
      Q4_K_M: { sizeGB: 404.4, bpw: 4.8, recSpeedGpu: 'Mac 512GB / CPU+GPU 混合' },
      'UD-Q2_K_XL': { sizeGB: 226.6, bpw: 2.7, recSpeedGpu: 'Mac 256GB 等級' }
    },
    sources: {
      arena: 'https://arena.ai/leaderboard/text/coding',
      specs: 'https://huggingface.co/deepseek-ai/DeepSeek-R1',
      benchmarks: 'https://huggingface.co/deepseek-ai/DeepSeek-R1（model card 評測表）',
      quant: 'https://huggingface.co/unsloth/DeepSeek-R1-GGUF'
    }
  },
  {
    id: 'deepseek-v3-moe',
    name: 'DeepSeek-V3 (MoE 671B)',
    family: 'DeepSeek',
    paramsTotal: 671.0,
    paramsActive: 37.0,
    architecture: 'MoE',
    license: 'MIT',
    commercialAllowed: true,
    contextWindow: 163840,
    nativeContext: 163840,
    arenaKey: 'deepseek-v3',
    arenaWebdevKey: null,
    arenaCodeElo: 1387.4,
    arenaWebdevElo: null,
    humanEval: null,
    sweBench: 42.0,
    liveCodeBench: null,
    tcGrade: 'S-',
    tcQuantMinBit: 'Q4_K_M / FP8',
    tcQuantNote: '已被 V3.2 與 V4 系列取代，保留作為對照。',
    jsonDisciplineScore: null,
    jsonNote: '支援標準 Tool Calling；未在繁中 Agent 考卷上實測。',
    kvPerTokKB: 68.6,
    speedPrefillScore: 82,
    speedDecodeRating: '未實測（啟用 37B）',
    workloadFit: { prefill: 4, decode: 5, agent: 4.8 },
    engineSupport: 'Production Merged',
    engineNotes: '主線全面支援 MLA / MoE。',
    storageAdvise: 'Q4_K_M 約 404 GB，需 NVMe 陣列。',
    examScore: null,
    isDay16Featured: false,
    day16Role: '上一代全能開源基座',
    editorial: 'tcGrade、workloadFit、speedPrefillScore 為 Day 16 作者評分',
    quantProfiles: {
      Q4_K_M: { sizeGB: 404.4, bpw: 4.8, recSpeedGpu: '工作站 512GB' },
      Q3_K_M: { sizeGB: 319.2, bpw: 3.8, recSpeedGpu: 'Mac 384GB 以上' }
    },
    sources: {
      arena: 'https://arena.ai/leaderboard/text/coding',
      specs: 'https://huggingface.co/deepseek-ai/DeepSeek-V3',
      benchmarks: 'https://huggingface.co/deepseek-ai/DeepSeek-V3（model card 評測表）',
      quant: 'https://huggingface.co/unsloth/DeepSeek-V3-GGUF'
    }
  },
  {
    id: 'gpt-oss-120b',
    name: 'gpt-oss-120b (MoE 117B / Active 5.1B)',
    family: 'GPT-OSS',
    paramsTotal: 116.8,
    paramsActive: 5.1,
    architecture: 'MoE',
    license: 'Apache 2.0',
    commercialAllowed: true,
    contextWindow: 131072,
    nativeContext: 131072,
    arenaKey: 'gpt-oss-120b',
    arenaWebdevKey: null,
    arenaCodeElo: 1390.6,
    arenaWebdevElo: null,
    humanEval: null,
    sweBench: 62.4,
    liveCodeBench: null,
    tcGrade: 'A-',
    tcQuantMinBit: 'MXFP4（原生）',
    tcQuantNote: '專家層原生就是 MXFP4，GGUF 各量化檔大小幾乎相同。Day 16 實測：GB10 上 llama.cpp 解碼 60.6 t/s。看啟用參數，不看總參數。',
    jsonDisciplineScore: null,
    jsonNote: 'harmony 格式關不掉思考；預設檔位在考卷上會把答案截斷，評測前要調 reasoning 設定。',
    kvPerTokKB: 36,
    speedPrefillScore: 84,
    speedDecodeRating: '極高速（GB10 llama.cpp 實測 60.6 t/s）',
    workloadFit: { prefill: 3.8, decode: 5, agent: 4.5 },
    engineSupport: 'Production Merged',
    engineNotes: 'llama.cpp 與 vLLM 已正式支援 MXFP4。',
    storageAdvise: '共存型主力，約 63 GB，放 NVMe 可十秒內冷啟動。',
    examScore: null,
    isDay16Featured: true,
    day16Role: 'Day 16 實測極速代表：60.6 t/s 解碼，短輸入長輸出的 MoE',
    editorial: 'tcGrade、workloadFit、speedPrefillScore 為 Day 16 作者評分',
    quantProfiles: {
      MXFP4: { sizeGB: 63.4, bpw: 4.3, recSpeedGpu: '60.6 t/s（GB10 llama.cpp，Day 16）' },
      Q4_K_M: { sizeGB: 62.8, bpw: 4.3, recSpeedGpu: '96 GB 以上' }
    },
    sources: {
      arena: 'https://arena.ai/leaderboard/text/coding',
      specs: 'https://huggingface.co/openai/gpt-oss-120b',
      benchmarks: 'https://arxiv.org/abs/2508.10925（SWE-bench Verified）',
      quant: 'https://huggingface.co/unsloth/gpt-oss-120b-GGUF',
      local: 'https://ithelp.ithome.com.tw/articles/10405898'
    }
  },
  {
    id: 'ornith-35b-a3b',
    name: 'Ornith 1.5 35B-A3B (MoE 36B / Active 3B)',
    family: 'Ornith',
    paramsTotal: 35.95,
    paramsActive: 3.0,
    architecture: 'MoE',
    license: 'MIT',
    commercialAllowed: true,
    contextWindow: 262144,
    nativeContext: 262144,
    arenaKey: null,
    arenaWebdevKey: null,
    arenaCodeElo: null,
    arenaWebdevElo: null,
    humanEval: null,
    sweBench: 79.0,
    liveCodeBench: null,
    tcGrade: 'A-',
    tcQuantMinBit: '8-bit 起步（BF16 最佳）',
    tcQuantNote: 'Day 15 考卷：BF16 繁中 20/20、簡體 0；NVFP4 掉到 19/20 且四輪有三輪洩漏簡體。Day 16 實測 8-bit 解碼 29.9 t/s。',
    jsonDisciplineScore: 52,
    jsonNote: 'Day 15 JSON 緊湊度：BF16 有 24/50 輪吐多行（NVFP4 為 40/50）。分數 = 100 × (1 − 多行輪數 / 50)。工具呼叫十輪全對。',
    jsonRecheckPending: '社群回報新版格式紀律已改善，作者尚未重測；重測前 Agent 篩選不以 Day 15 分數淘汰',
    kvPerTokKB: 20,
    speedPrefillScore: 82,
    speedDecodeRating: '高速（8-bit 實測 29.9 t/s）',
    workloadFit: { prefill: 3.5, decode: 4.8, agent: 5 },
    engineSupport: 'Production Merged',
    engineNotes: '架構同 Qwen3.6-35B-A3B（qwen3_5_moe），llama.cpp、vLLM 可直接載入。',
    storageAdvise: 'BF16 峰值佔用 120.7 GB（Day 16），128GB 機器可獨佔；Q8 約 38 GB 可共存。',
    examScore: '繁中 20/20・工具 10/10・多步 3/3（BF16）',
    isDay16Featured: true,
    day16Role: 'Day 16 獨佔/共存雙棲：KV 成本低、MIT 授權，128GB 機器適配',
    editorial: 'tcGrade、workloadFit、speedPrefillScore 為 Day 16 作者評分',
    quantProfiles: {
      BF16: { sizeGB: 71.9, bpw: 16.0, recSpeedGpu: '128GB 機器（峰值 120.7 GB）' },
      Q8_0: { sizeGB: 37.8, bpw: 8.4, recSpeedGpu: '29.9 t/s（GB10，Day 16）' },
      Q4_K_M: { sizeGB: 21.7, bpw: 4.8, recSpeedGpu: '24 GB 顯卡' }
    },
    sources: {
      arena: '不在 LMArena 榜上',
      specs: 'https://huggingface.co/ornith-ai/Ornith-1.5-35B-A3B',
      benchmarks: 'https://huggingface.co/ornith-ai/Ornith-1.5-35B-A3B（SWE-bench Verified）',
      local: 'https://github.com/ivanusto/llm-zhtw-agent-exam/blob/main/results/day15.md；https://ithelp.ithome.com.tw/articles/10405898'
    }
  },
  {
    id: 'qwen38-27b-dense',
    name: 'Qwen3.8-27B (Dense, Hybrid Attention)',
    family: 'Qwen',
    paramsTotal: 27.78,
    paramsActive: 27.78,
    architecture: 'Dense',
    license: 'Apache 2.0',
    commercialAllowed: true,
    contextWindow: 1048576,
    nativeContext: 262144,
    arenaKey: 'qwen3.8-27b',
    arenaWebdevKey: 'qwen3.8-27b',
    arenaCodeElo: 1499.1,
    arenaWebdevElo: 1593.3,
    humanEval: null,
    sweBench: null,
    liveCodeBench: 90.3,
    tcGrade: 'A',
    tcQuantMinBit: '8-bit 起步',
    tcQuantNote: 'Day 12 實測：q4_k_m 繁中 PPL 劣化 +0.842%、英文 +0.505%（1.67 倍）；8-bit 兩語言都無損。GB10 單路 decode：BF16 4.66、q8_0 7.93、q4_k_m 11.77 t/s（llama.cpp）。',
    jsonDisciplineScore: 100,
    jsonNote: 'Day 15 JSON 緊湊度 0/50 輪吐多行，是考卷上格式紀律最好的一款。',
    kvPerTokKB: 64,
    speedPrefillScore: 98,
    speedDecodeRating: '偏慢（8-bit 實測 7.9 t/s）',
    workloadFit: { prefill: 5, decode: 2.5, agent: 3.5 },
    engineSupport: 'Production Merged',
    engineNotes: 'vLLM 與 llama.cpp 已正式支援；官方另有 FP8 版。',
    storageAdvise: '住 NVMe SSD；大量 Prefill 吃記憶體頻寬。',
    examScore: '繁中 20/20・工具 10/10・多步 3/3（FP8）',
    isDay16Featured: true,
    day16Role: 'Day 16 典型 Prefill 神器：長文摘要與 RAG，長輸出慢',
    editorial: 'tcGrade、workloadFit、speedPrefillScore 為 Day 16 作者評分',
    quantProfiles: {
      BF16: { sizeGB: 55.6, bpw: 16.0, recSpeedGpu: '4.66 t/s（GB10 llama.cpp）' },
      Q8_0: { sizeGB: 29.0, bpw: 8.4, recSpeedGpu: '7.93 t/s（GB10 llama.cpp，Day 12）' },
      Q4_K_M: { sizeGB: 16.5, bpw: 4.8, recSpeedGpu: '11.77 t/s（GB10 llama.cpp，Day 12）' }
    },
    sources: {
      arena: 'https://arena.ai/leaderboard/text/coding；https://arena.ai/leaderboard/code/webdev',
      specs: 'https://huggingface.co/Qwen/Qwen3.8-27B',
      benchmarks: 'https://huggingface.co/Qwen/Qwen3.8-27B（LiveCodeBench v6）',
      quant: 'https://huggingface.co/unsloth/Qwen3.8-27B-GGUF',
      local: 'https://github.com/ivanusto/llm-zhtw-agent-exam/blob/main/results/day15.md；Day 12 量化實測'
    }
  },
  {
    id: 'flash-next-preview',
    name: 'Qwen3.8-Flash-Next (MoE 125B / Active 6B)',
    family: 'Qwen',
    paramsTotal: 125.0,
    paramsActive: 6.0,
    architecture: 'MoE',
    license: 'qwen-community-1.0',
    commercialAllowed: false,
    contextWindow: 1048576,
    nativeContext: 262144,
    arenaKey: null,
    arenaWebdevKey: 'qwen3.8-flash-next',
    arenaCodeElo: null,
    arenaWebdevElo: 1635.3,
    humanEval: null,
    sweBench: null,
    liveCodeBench: 91.9,
    tcGrade: 'B',
    tcQuantMinBit: '8-bit',
    tcQuantNote: 'Day 16 警示：整代架構升級的增益幾乎沒分給繁中。另有 51B n-gram embedding 與 4B MTP 不計入 125B。',
    jsonDisciplineScore: 52,
    jsonNote: 'Day 15 JSON 緊湊度 24/50 輪吐多行（UD-IQ4_XS）；工具呼叫十輪全對。',
    kvPerTokKB: 24,
    speedPrefillScore: 92,
    speedDecodeRating: '26.49 t/s（GB10 llama.cpp UD-IQ4_XS，Day 14）',
    workloadFit: { prefill: 4.2, decode: 3.5, agent: 3.0 },
    engineSupport: 'Experimental (PR Only)',
    engineNotes: 'Day 16（2026-08-28）時 vLLM 與 llama.cpp 支援都還在 PR，需自編分支；使用前請自行確認是否已合併。',
    storageAdvise: '實驗品放 NAS 集中庫即可。',
    examScore: '繁中 20/20・工具 10/10・多步 3/3（UD-IQ4_XS）',
    isDay16Featured: true,
    day16Role: 'Day 16 警示案例：官方基準領先、引擎支援仍在 PR，生產服務應避開',
    editorial: 'tcGrade、workloadFit、speedPrefillScore 為 Day 16 作者評分',
    quantProfiles: {
      BF16: { sizeGB: 360.0, bpw: 16.0, recSpeedGpu: '多卡資料中心' },
      Q8_0: { sizeGB: 188.2, bpw: 8.4, recSpeedGpu: 'Mac 256GB 以上' },
      'UD-Q4_K_XL': { sizeGB: 111.3, bpw: 4.9, recSpeedGpu: '128GB 機器吃四分之三記憶體' }
    },
    sources: {
      arena: 'https://arena.ai/leaderboard/code/webdev',
      specs: 'https://huggingface.co/Qwen/Qwen3.8-Flash-Next',
      benchmarks: 'https://huggingface.co/Qwen/Qwen3.8-Flash-Next（LiveCodeBench v6）',
      quant: 'https://huggingface.co/unsloth/Qwen3.8-Flash-Next-GGUF',
      local: 'https://github.com/ivanusto/llm-zhtw-agent-exam/blob/main/results/day14.md；https://github.com/ivanusto/llm-zhtw-agent-exam/blob/main/results/day15.md'
    }
  },
  {
    id: 'qwen25-coder-7b',
    name: 'Qwen2.5-Coder-7B-Instruct',
    family: 'Qwen',
    paramsTotal: 7.6,
    paramsActive: 7.6,
    architecture: 'Dense',
    license: 'Apache 2.0',
    commercialAllowed: true,
    contextWindow: 131072,
    nativeContext: 32768,
    arenaKey: null,
    arenaWebdevKey: null,
    arenaCodeElo: null,
    arenaWebdevElo: null,
    humanEval: 88.4,
    sweBench: null,
    liveCodeBench: null,
    tcGrade: 'B+',
    tcQuantMinBit: 'Q8_0 / FP16',
    tcQuantNote: '輕量端側主力，建議直上 8-bit 或 FP16 保繁中品質。',
    jsonDisciplineScore: null,
    jsonNote: '未在繁中 Agent 考卷上實測。',
    kvPerTokKB: 56,
    speedPrefillScore: 90,
    speedDecodeRating: '未實測（7B 密集）',
    workloadFit: { prefill: 4, decode: 4, agent: 4 },
    engineSupport: 'Production Merged',
    engineNotes: '所有端側框架開箱即用。',
    storageAdvise: 'Q8 約 8 GB，放哪裡都秒開。',
    examScore: null,
    isDay16Featured: false,
    day16Role: '共存型神隊友：給 ComfyUI 留顯存，自己只吃 5~8 GB',
    editorial: 'tcGrade、workloadFit、speedPrefillScore 為 Day 16 作者評分',
    quantProfiles: {
      BF16: { sizeGB: 15.2, bpw: 16.0, recSpeedGpu: '16 GB 顯卡' },
      Q8_0: { sizeGB: 8.1, bpw: 8.5, recSpeedGpu: '12 GB 顯卡' },
      Q4_K_M: { sizeGB: 4.7, bpw: 4.9, recSpeedGpu: '8 GB 顯卡' }
    },
    sources: {
      arena: '不在 LMArena coding 榜上',
      specs: 'https://huggingface.co/Qwen/Qwen2.5-Coder-7B-Instruct',
      benchmarks: 'https://arxiv.org/abs/2409.12186（Table 16，HumanEval）',
      quant: 'https://huggingface.co/bartowski/Qwen2.5-Coder-7B-Instruct-GGUF'
    }
  },
  {
    id: 'llama-33-70b',
    name: 'Llama-3.3-70B-Instruct',
    family: 'Llama',
    paramsTotal: 70.6,
    paramsActive: 70.6,
    architecture: 'Dense',
    license: 'Llama 3.3 Community',
    commercialAllowed: true,
    contextWindow: 131072,
    nativeContext: 131072,
    arenaKey: 'llama-3.3-70b-instruct',
    arenaWebdevKey: null,
    arenaCodeElo: 1345.9,
    arenaWebdevElo: null,
    humanEval: 88.4,
    sweBench: null,
    liveCodeBench: null,
    tcGrade: 'B+',
    tcQuantMinBit: '8-bit / imatrix Q4',
    tcQuantNote: '英文與邏輯強，繁中量化衰退比英文高，務必用 imatrix。',
    jsonDisciplineScore: null,
    jsonNote: '原生 Tool Calling 訓練；未在繁中 Agent 考卷上實測。',
    kvPerTokKB: 320,
    speedPrefillScore: 92,
    speedDecodeRating: '未實測（密集 70B，需大頻寬）',
    workloadFit: { prefill: 4.8, decode: 3.8, agent: 4.8 },
    engineSupport: 'Production Merged',
    engineNotes: '生態支援度最廣。',
    storageAdvise: '常駐主力放本機 NVMe。',
    examScore: null,
    isDay16Featured: false,
    day16Role: '上一代企業級 Dense 旗艦',
    editorial: 'tcGrade、workloadFit、speedPrefillScore 為 Day 16 作者評分',
    quantProfiles: {
      BF16: { sizeGB: 141.1, bpw: 16.0, recSpeedGpu: '2x 80G' },
      Q8_0: { sizeGB: 75.0, bpw: 8.5, recSpeedGpu: '96 GB 以上' },
      Q5_K_M: { sizeGB: 49.9, bpw: 5.7, recSpeedGpu: '64 GB 以上' },
      Q4_K_M: { sizeGB: 42.5, bpw: 4.8, recSpeedGpu: '雙卡 48 GB' }
    },
    sources: {
      arena: 'https://arena.ai/leaderboard/text/coding',
      specs: 'https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct',
      benchmarks: 'https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct（model card，HumanEval）',
      quant: 'https://huggingface.co/bartowski/Llama-3.3-70B-Instruct-GGUF'
    }
  },
  {
    id: 'codestral-22b',
    name: 'Codestral-22B-v0.1',
    family: 'Mistral',
    paramsTotal: 22.2,
    paramsActive: 22.2,
    architecture: 'Dense',
    license: 'MNCL (非商業專用 / 商用需授權)',
    commercialAllowed: false,
    contextWindow: 32768,
    nativeContext: 32768,
    arenaKey: null,
    arenaWebdevKey: null,
    arenaCodeElo: null,
    arenaWebdevElo: null,
    humanEval: 81.1,
    sweBench: null,
    liveCodeBench: null,
    tcGrade: 'B-',
    tcQuantMinBit: '8-bit',
    tcQuantNote: 'FIM 補全強，但繁中語感一般。',
    jsonDisciplineScore: null,
    jsonNote: 'FIM 專用模型；未在繁中 Agent 考卷上實測。',
    kvPerTokKB: 224,
    speedPrefillScore: 92,
    speedDecodeRating: '未實測（22B 密集）',
    workloadFit: { prefill: 4.2, decode: 3.5, agent: 3.8 },
    engineSupport: 'Production Merged',
    engineNotes: 'llama.cpp、vLLM 支援成熟。',
    storageAdvise: '本機 NVMe，適合常駐作為 IDE 後端。',
    examScore: null,
    isDay16Featured: false,
    day16Role: 'IDE 自動補全：80+ 種語言 FIM 特化',
    editorial: 'tcGrade、workloadFit、speedPrefillScore 為 Day 16 作者評分',
    quantProfiles: {
      BF16: { sizeGB: 44.5, bpw: 16.0, recSpeedGpu: '48 GB' },
      Q8_0: { sizeGB: 23.6, bpw: 8.5, recSpeedGpu: '24 GB 剛好' },
      Q4_K_M: { sizeGB: 13.3, bpw: 4.8, recSpeedGpu: '16 GB 顯卡' }
    },
    sources: {
      arena: '不在 LMArena coding 榜上',
      specs: 'https://huggingface.co/mistral-community/Codestral-22B-v0.1',
      benchmarks: 'https://mistral.ai/news/codestral（HumanEval）',
      quant: 'https://huggingface.co/bartowski/Codestral-22B-v0.1-GGUF'
    }
  },
  {
    id: 'gemma-2-27b',
    name: 'Gemma-2-27B-IT',
    family: 'Google Gemma',
    paramsTotal: 27.2,
    paramsActive: 27.2,
    architecture: 'Dense',
    license: 'Gemma License (允許商用)',
    commercialAllowed: true,
    contextWindow: 8192,
    nativeContext: 8192,
    arenaKey: 'gemma-2-27b-it',
    arenaWebdevKey: null,
    arenaCodeElo: 1304.6,
    arenaWebdevElo: null,
    humanEval: null,
    sweBench: null,
    liveCodeBench: null,
    tcGrade: 'B+',
    tcQuantMinBit: '8-bit 起步',
    tcQuantNote: '上下文只有 8k；已被 Gemma 4 取代。',
    jsonDisciplineScore: null,
    jsonNote: '未在繁中 Agent 考卷上實測。',
    kvPerTokKB: 184,
    speedPrefillScore: 94,
    speedDecodeRating: '未實測',
    workloadFit: { prefill: 4.5, decode: 3.0, agent: 3.2 },
    engineSupport: 'Production Merged',
    engineNotes: 'llama.cpp 與 vLLM 支援 soft-capping 與滑動窗口。',
    storageAdvise: '本機 NVMe。',
    examScore: null,
    isDay16Featured: false,
    day16Role: '上一代 Google Dense',
    editorial: 'tcGrade、workloadFit、speedPrefillScore 為 Day 16 作者評分',
    quantProfiles: {
      BF16: { sizeGB: 54.5, bpw: 16.0, recSpeedGpu: '64 GB' },
      Q5_K_M: { sizeGB: 19.4, bpw: 5.7, recSpeedGpu: '24 GB' },
      Q4_K_M: { sizeGB: 16.6, bpw: 4.9, recSpeedGpu: '24 GB 順暢' }
    },
    sources: {
      arena: 'https://arena.ai/leaderboard/text/coding',
      specs: 'https://huggingface.co/google/gemma-2-27b-it',
      quant: 'https://huggingface.co/bartowski/gemma-2-27b-it-GGUF'
    }
  },
  {
    id: 'yi-coder-9b',
    name: 'Yi-Coder-9B-Chat',
    family: 'Yi',
    paramsTotal: 8.8,
    paramsActive: 8.8,
    architecture: 'Dense',
    license: 'Apache 2.0',
    commercialAllowed: true,
    contextWindow: 131072,
    nativeContext: 131072,
    arenaKey: null,
    arenaWebdevKey: null,
    arenaCodeElo: null,
    arenaWebdevElo: null,
    humanEval: 85.4,
    sweBench: null,
    liveCodeBench: null,
    tcGrade: 'A-',
    tcQuantMinBit: 'Q8_0 / FP16',
    tcQuantNote: '中文原生血統，128k 長文本。',
    jsonDisciplineScore: null,
    jsonNote: '未在繁中 Agent 考卷上實測。',
    kvPerTokKB: 96,
    speedPrefillScore: 88,
    speedDecodeRating: '未實測（9B 密集）',
    workloadFit: { prefill: 4.2, decode: 4.0, agent: 4.0 },
    engineSupport: 'Production Merged',
    engineNotes: '全面支援。',
    storageAdvise: 'Q8 約 9.4 GB，本機或 NAS 皆可。',
    examScore: null,
    isDay16Featured: false,
    day16Role: '上一代端側中文程式碼模型',
    editorial: 'tcGrade、workloadFit、speedPrefillScore 為 Day 16 作者評分',
    quantProfiles: {
      BF16: { sizeGB: 17.7, bpw: 16.1, recSpeedGpu: '24 GB' },
      Q8_0: { sizeGB: 9.4, bpw: 8.5, recSpeedGpu: '12 GB' },
      Q4_K_M: { sizeGB: 5.3, bpw: 4.8, recSpeedGpu: '8 GB' }
    },
    sources: {
      arena: '不在 LMArena coding 榜上',
      specs: 'https://huggingface.co/01-ai/Yi-Coder-9B-Chat',
      benchmarks: 'https://github.com/01-ai/Yi-Coder（HumanEval）',
      quant: 'https://huggingface.co/bartowski/Yi-Coder-9B-Chat-GGUF'
    }
  },
  {
    id: 'deepseek-v4-flash',
    name: 'DeepSeek-V4-Flash (MoE 284B / Active 13B)',
    family: 'DeepSeek',
    paramsTotal: 284.0,
    paramsActive: 13.0,
    architecture: 'MoE',
    license: 'MIT',
    commercialAllowed: true,
    contextWindow: 1048576,
    nativeContext: 1048576,
    arenaKey: 'deepseek-v4-flash',
    arenaWebdevKey: 'deepseek-v4-flash-high',
    arenaCodeElo: 1483.1,
    arenaWebdevElo: 1580.2,
    humanEval: 69.5,
    sweBench: 79.0,
    liveCodeBench: 91.6,
    tcGrade: '未評',
    tcQuantMinBit: '原生 FP4+FP8',
    tcQuantNote: 'HumanEval 69.5 是 base 模型數字；SWE-bench 與 LiveCodeBench 取官方 Max 檔位。本機雙機 GB10（vLLM TP=2、DSpark 投機解碼）典型 decode 約 40 t/s，16K 與 49K token 針取回正確。',
    jsonDisciplineScore: null,
    jsonNote: '工具呼叫 finish_reason 正確；未跑繁中 Agent 考卷。',
    kvPerTokKB: 5.4,
    speedPrefillScore: 84,
    speedDecodeRating: '約 40 t/s（雙機 GB10、vLLM TP=2、DSpark 投機解碼）',
    workloadFit: { prefill: 3.8, decode: 4.0, agent: 3.9 },
    engineSupport: 'Production Merged',
    engineNotes: '上游 vLLM 原生支援（CSA/HCA 混合注意力）；ds4 引擎有專用 GGUF。',
    storageAdvise: '原生權重約 160 GB，單台 128GB 放不下，需雙機或 256GB 以上。',
    examScore: null,
    isDay16Featured: false,
    day16Role: 'Day 17 ds4 與 Day 27 雙機篇的主力模型',
    editorial: 'workloadFit、speedPrefillScore 依規則產生（架構與啟用參數量）；tcGrade 未評',
    quantProfiles: {
      'FP4+FP8': { sizeGB: 159.6, bpw: 4.4, recSpeedGpu: '約 40 t/s（雙機 GB10 vLLM TP=2）' },
      'UD-Q4_K_XL': { sizeGB: 155.1, bpw: 4.3, recSpeedGpu: '256 GB 以上' }
    },
    sources: {
      arena: 'https://arena.ai/leaderboard/text/coding；https://arena.ai/leaderboard/code/webdev',
      specs: 'https://huggingface.co/deepseek-ai/DeepSeek-V4-Flash',
      benchmarks: 'https://huggingface.co/deepseek-ai/DeepSeek-V4-Flash（model card 評測表）',
      quant: 'https://huggingface.co/unsloth/DeepSeek-V4-Flash-0731-GGUF',
      local: '作者雙機 GB10 實測（2026-09-02）；KV 為依 config 粗估'
    }
  },
  {
    id: 'muse-glimmer-30b',
    name: 'Muse-Glimmer-30B (Dense 30B)',
    family: 'Muse',
    paramsTotal: 29.6,
    paramsActive: 29.6,
    architecture: 'Dense',
    license: 'Apache 2.0',
    commercialAllowed: true,
    contextWindow: 131072,
    nativeContext: 131072,
    arenaKey: 'muse-glimmer',
    arenaWebdevKey: 'muse-glimmer',
    arenaCodeElo: 1482.7,
    arenaWebdevElo: 1359.7,
    humanEval: null,
    sweBench: 76.0,
    liveCodeBench: null,
    tcGrade: 'A',
    tcQuantMinBit: '8-bit 起步（低位元認明 imatrix）',
    tcQuantNote: '含約 1.8B 視覺編碼器。GB10 上 NVFP4 無投機解碼 12.57 t/s（vLLM）。',
    jsonDisciplineScore: null,
    jsonNote: '未跑繁中 Agent 考卷。',
    kvPerTokKB: 13,
    speedPrefillScore: 92,
    speedDecodeRating: '12.57 t/s（GB10 vLLM NVFP4、無投機解碼）',
    workloadFit: { prefill: 4.8, decode: 3.8, agent: 4.4 },
    engineSupport: 'Production Merged',
    engineNotes: '官方提供 GGUF；滑動窗口加全域注意力，KV 只有 13 層全域層吃長度。',
    storageAdvise: 'Q4 約 17 GB，本機 NVMe 秒開。',
    examScore: null,
    isDay16Featured: false,
    day16Role: '密集 30B 級新星：KV 成本低，長輸入吞吐強',
    editorial: 'tcGrade、workloadFit、speedPrefillScore 為 Day 16 作者評分',
    quantProfiles: {
      BF16: { sizeGB: 59.6, bpw: 16.1, recSpeedGpu: '64 GB' },
      Q8_0: { sizeGB: 29.6, bpw: 8.0, recSpeedGpu: '32 GB' },
      Q4_K_M: { sizeGB: 16.8, bpw: 4.5, recSpeedGpu: '24 GB 顯卡' }
    },
    sources: {
      arena: 'https://arena.ai/leaderboard/text/coding；https://arena.ai/leaderboard/code/webdev',
      specs: 'https://huggingface.co/meta-models/Muse-Glimmer-30B',
      benchmarks: 'https://huggingface.co/meta-models/Muse-Glimmer-30B（SWE-Bench Verified）',
      quant: 'https://huggingface.co/meta-models/Muse-Glimmer-30B-GGUF',
      local: '作者 GB10 實測'
    }
  },
  {
    id: 'deepseek-v41-flash',
    name: 'DeepSeek-V4.1-Flash (MoE 552B + Engram / Active 16B)',
    family: 'DeepSeek',
    paramsTotal: 763.2,
    paramsActive: 16.0,
    architecture: 'MoE',
    license: 'MIT',
    commercialAllowed: true,
    contextWindow: 1048576,
    nativeContext: 1048576,
    arenaKey: null,
    arenaWebdevKey: 'deepseek-v4.1-flash-max',
    arenaCodeElo: null,
    arenaWebdevElo: 1614.0,
    humanEval: 79.4,
    sweBench: null,
    liveCodeBench: null,
    tcGrade: '未評',
    tcQuantMinBit: '2.9 bpw 以上（2.0 bpw 長對話會亂）',
    tcQuantNote: '總參數 763B = 552B 主幹 + 196B Engram 條件記憶；decode 啟用 16B、prefill 8B。本機雙機 GB10 實測：EXL3 2.0bpw 在上下文約 55K 以後語無倫次，換 MiaAI 2.9bpw 後長任務正常；2.9bpw 與 ds4 Q2 在 79K~82K 繁中長文皆無簡體字。',
    jsonDisciplineScore: null,
    jsonNote: '工具呼叫與回填正確、14.9K 與 45.5K token 針取回正確；未跑繁中 Agent 考卷。ds4 下思考預設開啟，關閉要送 think:false。',
    kvPerTokKB: 0.87,
    speedPrefillScore: 84,
    speedDecodeRating: '26.0 t/s（雙機 GB10、vLLM EXL3 2.9bpw、DSpark k=3、temperature 0）',
    workloadFit: { prefill: 3.8, decode: 4.0, agent: 3.9 },
    engineSupport: 'Experimental (Community Recipe)',
    engineNotes: 'llama.cpp 主線跑不動；可行路線是社群 vLLM EXL3 配方（MiaAI-Lab）或 ds4 引擎的 Q2 GGUF。雙機載入 EXL3 約 75 分鐘，ds4 只要 2 分鐘但最多 2 個 session。',
    storageAdvise: '原生 510 GB；EXL3 2.9bpw 約 196 GiB、ds4 Q2 約 366 GB，至少要雙機 GB10 或 512GB 等級機器。',
    examScore: null,
    isDay16Featured: false,
    day16Role: '2026-09 最新 DeepSeek：Engram 條件記憶與 CSA2 稀疏注意力，KV 成本只有 V4-Flash 的約 1/4',
    editorial: 'workloadFit、speedPrefillScore 依規則產生（架構與啟用參數量）；tcGrade 未評',
    quantProfiles: {
      'FP8+FP4': { sizeGB: 510.3, bpw: 5.3, recSpeedGpu: '多卡資料中心' },
      'Q2 (ds4)': { sizeGB: 365.7, bpw: 3.8, recSpeedGpu: '21.4 t/s 單路（雙機 GB10 ds4 RDMA TP、think:false、temperature 0）' },
      'EXL3 2.9bpw': { sizeGB: 210.4, bpw: 2.2, recSpeedGpu: '26.0 t/s（雙機 GB10 vLLM、DSpark k=3、temperature 0）' }
    },
    sources: {
      arena: 'https://arena.ai/leaderboard/code/webdev',
      specs: 'https://huggingface.co/deepseek-ai/DeepSeek-V4.1-Flash',
      benchmarks: 'https://huggingface.co/deepseek-ai/DeepSeek-V4.1-Flash（HumanEval 為 base 模型）',
      quant: 'https://huggingface.co/antirez/deepseek-v4.1-flash-gguf',
      local: '作者雙機 GB10 實測（2026-09-13 至 09-16）；KV 取自 model card 的 890 bytes/token（FP4 主 KV）'
    }
  },
  {
    id: 'deepseek-v4-pro',
    name: 'DeepSeek-V4-Pro-0813 (MoE 1.6T / Active 49B)',
    family: 'DeepSeek',
    paramsTotal: 1600.0,
    paramsActive: 49.0,
    architecture: 'MoE',
    license: 'MIT',
    commercialAllowed: true,
    contextWindow: 1048576,
    nativeContext: 1048576,
    arenaKey: 'deepseek-v4-pro-high-20260813',
    arenaWebdevKey: 'deepseek-v4-pro-high-20260813',
    arenaCodeElo: 1503.4,
    arenaWebdevElo: 1580.5,
    humanEval: 76.8,
    sweBench: 80.6,
    liveCodeBench: 93.5,
    tcGrade: '未評',
    tcQuantMinBit: '8-bit 起步（繁中通則）',
    tcQuantNote: 'HumanEval 76.8 是 base 模型數字；SWE-bench 與 LiveCodeBench 取官方 Max 檔位。',
    jsonDisciplineScore: null,
    jsonNote: '未在繁中 Agent 考卷上實測。',
    kvPerTokKB: 7.7,
    speedPrefillScore: 84,
    speedDecodeRating: '未實測（啟用 49.0B）',
    workloadFit: { prefill: 3.8, decode: 3.5, agent: 3.6 },
    engineSupport: 'Production Merged',
    engineNotes: '與 V4-Flash 同架構，上游 vLLM 支援。',
    storageAdvise: '約 893 GB，資料中心等級。',
    examScore: null,
    isDay16Featured: false,
    day16Role: '開放權重的 SWE-bench 頂端之一，本地部署門檻極高',
    editorial: 'workloadFit、speedPrefillScore 依規則產生（架構與啟用參數量）；tcGrade 未評',
    quantProfiles: {
      'FP4+FP8': { sizeGB: 892.7, bpw: 4.5, recSpeedGpu: '多卡資料中心' }
    },
    sources: {
      arena: 'https://arena.ai/leaderboard/text/coding；https://arena.ai/leaderboard/code/webdev',
      specs: 'https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro-0813',
      benchmarks: 'https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro（model card 評測表）',
      local: 'KV 為依 config 粗估'
    }
  },
  {
    id: 'qwen36-35b-a3b',
    name: 'Qwen3.6-35B-A3B (MoE 35B / Active 3B)',
    family: 'Qwen',
    paramsTotal: 35.0,
    paramsActive: 3.0,
    architecture: 'MoE',
    license: 'Apache 2.0',
    commercialAllowed: true,
    contextWindow: 1010000,
    nativeContext: 262144,
    arenaKey: null,
    arenaWebdevKey: null,
    arenaCodeElo: null,
    arenaWebdevElo: null,
    humanEval: null,
    sweBench: 73.4,
    liveCodeBench: 80.4,
    tcGrade: '未評',
    tcQuantMinBit: '8-bit 起步（繁中通則）',
    tcQuantNote: '與 Ornith 1.5 同架構（Ornith 是它的衍生）。GB10 上 12K token prefill 4.34 秒（2,795.8 tok/s）。',
    jsonDisciplineScore: null,
    jsonNote: '未在繁中 Agent 考卷上實測。',
    kvPerTokKB: 20,
    speedPrefillScore: 84,
    speedDecodeRating: '未實測（啟用 3.0B）',
    workloadFit: { prefill: 3.8, decode: 4.8, agent: 4.3 },
    engineSupport: 'Production Merged',
    engineNotes: 'vLLM、llama.cpp 正式支援；unsloth 已發布 GGUF。',
    storageAdvise: 'Q4 約 22 GB，共存型首選之一。',
    examScore: null,
    isDay16Featured: false,
    day16Role: '小啟用量 MoE：Apache 授權，16~24GB 顯卡可跑的 agent 型模型',
    editorial: 'workloadFit、speedPrefillScore 依規則產生（架構與啟用參數量）；tcGrade 未評',
    quantProfiles: {
      BF16: { sizeGB: 71.9, bpw: 16.4, recSpeedGpu: '96 GB 以上' },
      Q8_0: { sizeGB: 36.9, bpw: 8.4, recSpeedGpu: '48 GB 以上' },
      Q4_K_M: { sizeGB: 22.1, bpw: 5.1, recSpeedGpu: '24 GB 顯卡' }
    },
    sources: {
      arena: '不在 LMArena coding 榜上',
      specs: 'https://huggingface.co/Qwen/Qwen3.6-35B-A3B',
      benchmarks: 'https://huggingface.co/Qwen/Qwen3.6-35B-A3B（model card）',
      quant: 'https://huggingface.co/unsloth/Qwen3.6-35B-A3B-GGUF',
      local: '作者 GB10 prefill 實測'
    }
  },
  {
    id: 'qwen3-coder-next',
    name: 'Qwen3-Coder-Next (MoE 80B / Active 3B)',
    family: 'Qwen',
    paramsTotal: 80.0,
    paramsActive: 3.0,
    architecture: 'MoE',
    license: 'Apache 2.0',
    commercialAllowed: true,
    contextWindow: 262144,
    nativeContext: 262144,
    arenaKey: null,
    arenaWebdevKey: null,
    arenaCodeElo: null,
    arenaWebdevElo: null,
    humanEval: null,
    sweBench: null,
    liveCodeBench: null,
    tcGrade: '未評',
    tcQuantMinBit: '8-bit 起步（繁中通則）',
    tcQuantNote: '程式碼特化；model card 的評測只有圖片，沒有可引用的數字。',
    jsonDisciplineScore: null,
    jsonNote: '未在繁中 Agent 考卷上實測。',
    kvPerTokKB: 24,
    speedPrefillScore: 84,
    speedDecodeRating: '未實測（啟用 3.0B）',
    workloadFit: { prefill: 3.8, decode: 4.8, agent: 4.3 },
    engineSupport: 'Production Merged',
    engineNotes: 'unsloth 已發布 GGUF；vLLM 支援 Qwen3-Next 架構。',
    storageAdvise: 'Q4 約 49 GB，64GB 機器可跑。',
    examScore: null,
    isDay16Featured: false,
    day16Role: '程式碼特化的小啟用量 MoE',
    editorial: 'workloadFit、speedPrefillScore 依規則產生（架構與啟用參數量）；tcGrade 未評',
    quantProfiles: {
      BF16: { sizeGB: 159.4, bpw: 15.9, recSpeedGpu: '192 GB 以上' },
      Q8_0: { sizeGB: 84.8, bpw: 8.5, recSpeedGpu: '96 GB 以上' },
      Q4_K_M: { sizeGB: 48.5, bpw: 4.8, recSpeedGpu: '64 GB' }
    },
    sources: {
      arena: '不在 LMArena coding 榜上',
      specs: 'https://huggingface.co/Qwen/Qwen3-Coder-Next',
      quant: 'https://huggingface.co/unsloth/Qwen3-Coder-Next-GGUF'
    }
  },
  {
    id: 'gemma-4-31b',
    name: 'Gemma-4-31B-IT (Dense 31B)',
    family: 'Google Gemma',
    paramsTotal: 31.27,
    paramsActive: 31.27,
    architecture: 'Dense',
    license: 'Apache 2.0',
    commercialAllowed: true,
    contextWindow: 262144,
    nativeContext: 262144,
    arenaKey: 'gemma-4-31b',
    arenaWebdevKey: 'gemma-4-31b',
    arenaCodeElo: 1498.8,
    arenaWebdevElo: 1364.1,
    humanEval: null,
    sweBench: null,
    liveCodeBench: 80.0,
    tcGrade: '未評',
    tcQuantMinBit: '8-bit 起步（繁中通則）',
    tcQuantNote: '50 層滑動窗口（1024）加 10 層全域；KV 只算全域層，滑動層另有約 800 KB/token 但上限 1024 token。',
    jsonDisciplineScore: null,
    jsonNote: '未在繁中 Agent 考卷上實測。',
    kvPerTokKB: 80,
    speedPrefillScore: 92,
    speedDecodeRating: '未實測（啟用 31.27B）',
    workloadFit: { prefill: 4.5, decode: 3.0, agent: 3.8 },
    engineSupport: 'Production Merged',
    engineNotes: 'vLLM、llama.cpp 正式支援；unsloth 已發布 GGUF。',
    storageAdvise: 'Q4 約 18 GB，24GB 顯卡可跑。',
    examScore: null,
    isDay16Featured: false,
    day16Role: 'Google 新一代 Dense，Apache 授權',
    editorial: 'workloadFit、speedPrefillScore 依規則產生（架構與啟用參數量）；tcGrade 未評',
    quantProfiles: {
      BF16: { sizeGB: 62.5, bpw: 16.0, recSpeedGpu: '64 GB 以上' },
      Q8_0: { sizeGB: 32.6, bpw: 8.3, recSpeedGpu: '48 GB' },
      Q4_K_M: { sizeGB: 18.3, bpw: 4.7, recSpeedGpu: '24 GB 顯卡' }
    },
    sources: {
      arena: 'https://arena.ai/leaderboard/text/coding；https://arena.ai/leaderboard/code/webdev',
      specs: 'https://huggingface.co/google/gemma-4-31B-it',
      benchmarks: 'https://huggingface.co/google/gemma-4-31B-it（LiveCodeBench v6）',
      quant: 'https://huggingface.co/unsloth/gemma-4-31B-it-GGUF'
    }
  },
  {
    id: 'gemma-4-26b-a4b',
    name: 'Gemma-4-26B-A4B-IT (MoE 25B / Active 3.8B)',
    family: 'Google Gemma',
    paramsTotal: 25.2,
    paramsActive: 3.8,
    architecture: 'MoE',
    license: 'Apache 2.0',
    commercialAllowed: true,
    contextWindow: 262144,
    nativeContext: 262144,
    arenaKey: 'gemma-4-26b-a4b',
    arenaWebdevKey: 'gemma-4-26b-a4b',
    arenaCodeElo: 1480.8,
    arenaWebdevElo: 1361.4,
    humanEval: null,
    sweBench: null,
    liveCodeBench: 77.1,
    tcGrade: '未評',
    tcQuantMinBit: '8-bit 起步（繁中通則）',
    tcQuantNote: '25 層滑動窗口加 5 層全域，KV 只算全域層。',
    jsonDisciplineScore: null,
    jsonNote: '未在繁中 Agent 考卷上實測。',
    kvPerTokKB: 20,
    speedPrefillScore: 84,
    speedDecodeRating: '未實測（啟用 3.8B）',
    workloadFit: { prefill: 3.8, decode: 4.8, agent: 4.3 },
    engineSupport: 'Production Merged',
    engineNotes: 'vLLM、llama.cpp 正式支援；unsloth 已發布 GGUF。',
    storageAdvise: 'Q4 約 17 GB，16~24GB 顯卡可跑。',
    examScore: null,
    isDay16Featured: false,
    day16Role: 'Google 小啟用量 MoE：16GB 級顯卡的高速選項',
    editorial: 'workloadFit、speedPrefillScore 依規則產生（架構與啟用參數量）；tcGrade 未評',
    quantProfiles: {
      BF16: { sizeGB: 51.6, bpw: 16.4, recSpeedGpu: '64 GB' },
      Q8_0: { sizeGB: 26.9, bpw: 8.5, recSpeedGpu: '32 GB' },
      Q4_K_M: { sizeGB: 17.0, bpw: 5.4, recSpeedGpu: '24 GB 顯卡' }
    },
    sources: {
      arena: 'https://arena.ai/leaderboard/text/coding；https://arena.ai/leaderboard/code/webdev',
      specs: 'https://huggingface.co/google/gemma-4-26B-A4B-it',
      benchmarks: 'https://huggingface.co/google/gemma-4-26B-A4B-it（LiveCodeBench v6）',
      quant: 'https://huggingface.co/unsloth/gemma-4-26B-A4B-it-GGUF'
    }
  },
  {
    id: 'gpt-oss-20b',
    name: 'gpt-oss-20b (MoE 21B / Active 3.6B)',
    family: 'GPT-OSS',
    paramsTotal: 20.9,
    paramsActive: 3.6,
    architecture: 'MoE',
    license: 'Apache 2.0',
    commercialAllowed: true,
    contextWindow: 131072,
    nativeContext: 131072,
    arenaKey: 'gpt-oss-20b',
    arenaWebdevKey: null,
    arenaCodeElo: 1369.2,
    arenaWebdevElo: null,
    humanEval: null,
    sweBench: null,
    liveCodeBench: null,
    tcGrade: '未評',
    tcQuantMinBit: 'MXFP4（原生）',
    tcQuantNote: '專家層原生 MXFP4，16GB 顯卡可全放。',
    jsonDisciplineScore: null,
    jsonNote: 'harmony 格式關不掉思考；未在繁中 Agent 考卷上實測。',
    kvPerTokKB: 24,
    speedPrefillScore: 84,
    speedDecodeRating: '未實測（啟用 3.6B）',
    workloadFit: { prefill: 3.8, decode: 4.8, agent: 4.3 },
    engineSupport: 'Production Merged',
    engineNotes: 'llama.cpp 與 vLLM 正式支援 MXFP4。',
    storageAdvise: '約 12 GB，放哪裡都快。',
    examScore: null,
    isDay16Featured: false,
    day16Role: '16GB 顯卡的 gpt-oss',
    editorial: 'workloadFit、speedPrefillScore 依規則產生（架構與啟用參數量）；tcGrade 未評',
    quantProfiles: {
      MXFP4: { sizeGB: 12.1, bpw: 4.6, recSpeedGpu: '16 GB 顯卡' },
      Q4_K_M: { sizeGB: 11.6, bpw: 4.4, recSpeedGpu: '16 GB 顯卡' }
    },
    sources: {
      arena: 'https://arena.ai/leaderboard/text/coding',
      specs: 'https://huggingface.co/openai/gpt-oss-20b',
      quant: 'https://huggingface.co/unsloth/gpt-oss-20b-GGUF'
    }
  },
  {
    id: 'devstral-small-2',
    name: 'Devstral-Small-2-24B-Instruct-2512 (Dense 24B)',
    family: 'Mistral',
    paramsTotal: 24.0,
    paramsActive: 24.0,
    architecture: 'Dense',
    license: 'Apache 2.0',
    commercialAllowed: true,
    contextWindow: 262144,
    nativeContext: 262144,
    arenaKey: null,
    arenaWebdevKey: null,
    arenaCodeElo: null,
    arenaWebdevElo: null,
    humanEval: null,
    sweBench: 68.0,
    liveCodeBench: null,
    tcGrade: '未評',
    tcQuantMinBit: '8-bit 起步（繁中通則）',
    tcQuantNote: '程式碼 agent 特化；標準 GQA，長上下文的 KV 成本高。',
    jsonDisciplineScore: null,
    jsonNote: '未在繁中 Agent 考卷上實測。',
    kvPerTokKB: 160,
    speedPrefillScore: 92,
    speedDecodeRating: '未實測（啟用 24.0B）',
    workloadFit: { prefill: 4.5, decode: 3.0, agent: 3.8 },
    engineSupport: 'Production Merged',
    engineNotes: 'vLLM、llama.cpp 正式支援；unsloth 已發布 GGUF。',
    storageAdvise: 'Q4 約 14 GB，16GB 顯卡可跑（上下文要收小）。',
    examScore: null,
    isDay16Featured: false,
    day16Role: '16~24GB 顯卡的程式碼 agent 模型',
    editorial: 'workloadFit、speedPrefillScore 依規則產生（架構與啟用參數量）；tcGrade 未評',
    quantProfiles: {
      Q8_0: { sizeGB: 25.1, bpw: 8.4, recSpeedGpu: '32 GB' },
      Q4_K_M: { sizeGB: 14.3, bpw: 4.8, recSpeedGpu: '16 GB 顯卡' }
    },
    sources: {
      arena: '不在 LMArena coding 榜上',
      specs: 'https://huggingface.co/mistralai/Devstral-Small-2-24B-Instruct-2512',
      benchmarks: 'https://huggingface.co/mistralai/Devstral-Small-2-24B-Instruct-2512（SWE-bench Verified）',
      quant: 'https://huggingface.co/unsloth/Devstral-Small-2-24B-Instruct-2512-GGUF'
    }
  },
  {
    id: 'mistral-small-4',
    name: 'Mistral-Small-4-119B-2603 (MoE 119B / Active 6.5B)',
    family: 'Mistral',
    paramsTotal: 119.0,
    paramsActive: 6.5,
    architecture: 'MoE',
    license: 'Apache 2.0',
    commercialAllowed: true,
    contextWindow: 262144,
    nativeContext: 262144,
    arenaKey: null,
    arenaWebdevKey: null,
    arenaCodeElo: null,
    arenaWebdevElo: null,
    humanEval: null,
    sweBench: null,
    liveCodeBench: null,
    tcGrade: '未評',
    tcQuantMinBit: '8-bit 起步（繁中通則）',
    tcQuantNote: 'MLA 注意力，KV 成本低；model card 的程式碼評測只有圖片。',
    jsonDisciplineScore: null,
    jsonNote: '未在繁中 Agent 考卷上實測。',
    kvPerTokKB: 22.5,
    speedPrefillScore: 84,
    speedDecodeRating: '未實測（啟用 6.5B）',
    workloadFit: { prefill: 3.8, decode: 4.5, agent: 4.2 },
    engineSupport: 'Production Merged',
    engineNotes: 'unsloth 已發布 GGUF；vLLM 支援。',
    storageAdvise: 'Q4 約 74 GB，128GB 機器可共存。',
    examScore: null,
    isDay16Featured: false,
    day16Role: '128GB 機器的 Apache 授權 MoE 選項',
    editorial: 'workloadFit、speedPrefillScore 依規則產生（架構與啟用參數量）；tcGrade 未評',
    quantProfiles: {
      Q8_0: { sizeGB: 126.5, bpw: 8.5, recSpeedGpu: '192 GB 以上' },
      Q4_K_M: { sizeGB: 73.8, bpw: 5.0, recSpeedGpu: '96~128 GB' }
    },
    sources: {
      arena: '不在 LMArena coding 榜上',
      specs: 'https://huggingface.co/mistralai/Mistral-Small-4-119B-2603',
      quant: 'https://huggingface.co/unsloth/Mistral-Small-4-119B-2603-GGUF'
    }
  },
  {
    id: 'mistral-medium-35',
    name: 'Mistral-Medium-3.5-128B (Dense 128B)',
    family: 'Mistral',
    paramsTotal: 127.7,
    paramsActive: 127.7,
    architecture: 'Dense',
    license: 'Modified MIT (大型企業有營收門檻)',
    commercialAllowed: false,
    contextWindow: 262144,
    nativeContext: 262144,
    arenaKey: 'mistral-medium-3.5',
    arenaWebdevKey: 'mistral-medium-3.5',
    arenaCodeElo: 1478.8,
    arenaWebdevElo: 1264.9,
    humanEval: null,
    sweBench: 77.6,
    liveCodeBench: null,
    tcGrade: '未評',
    tcQuantMinBit: '8-bit 起步（繁中通則）',
    tcQuantNote: 'model card 警告：在 commit c4be198 之前的 config 做出的 GGUF 會損失長上下文品質。',
    jsonDisciplineScore: null,
    jsonNote: '未在繁中 Agent 考卷上實測。',
    kvPerTokKB: 352,
    speedPrefillScore: 92,
    speedDecodeRating: '未實測（啟用 127.7B）',
    workloadFit: { prefill: 4.5, decode: 2.5, agent: 3.5 },
    engineSupport: 'Production Merged',
    engineNotes: 'unsloth 已發布 GGUF；注意 GGUF 版本。',
    storageAdvise: 'Q4 約 75 GB；密集 128B 在 GB10 級頻寬上 decode 很慢。',
    examScore: null,
    isDay16Featured: false,
    day16Role: '大型密集模型：SWE-bench 高，但授權對大企業有限制',
    editorial: 'workloadFit、speedPrefillScore 依規則產生（架構與啟用參數量）；tcGrade 未評',
    quantProfiles: {
      Q8_0: { sizeGB: 132.9, bpw: 8.3, recSpeedGpu: '192 GB 以上' },
      Q4_K_M: { sizeGB: 74.9, bpw: 4.7, recSpeedGpu: '96~128 GB' }
    },
    sources: {
      arena: 'https://arena.ai/leaderboard/text/coding；https://arena.ai/leaderboard/code/webdev',
      specs: 'https://huggingface.co/mistralai/Mistral-Medium-3.5-128B',
      benchmarks: 'https://huggingface.co/mistralai/Mistral-Medium-3.5-128B（SWE-Bench Verified）',
      quant: 'https://huggingface.co/unsloth/Mistral-Medium-3.5-128B-GGUF'
    }
  },
  {
    id: 'llama-4-scout',
    name: 'Llama-4-Scout-17B-16E-Instruct (MoE 109B / Active 17B)',
    family: 'Llama',
    paramsTotal: 108.6,
    paramsActive: 17.0,
    architecture: 'MoE',
    license: 'Llama 4 Community',
    commercialAllowed: true,
    contextWindow: 10485760,
    nativeContext: 10485760,
    arenaKey: 'llama-4-scout-17b-16e-instruct',
    arenaWebdevKey: null,
    arenaCodeElo: 1362.3,
    arenaWebdevElo: null,
    humanEval: null,
    sweBench: null,
    liveCodeBench: 32.8,
    tcGrade: '未評',
    tcQuantMinBit: '8-bit 起步（繁中通則）',
    tcQuantNote: '36 層 chunked local（8192）加 12 層全域，KV 只算全域層。LiveCodeBench 為 2024/10~2025/02 區間。',
    jsonDisciplineScore: null,
    jsonNote: '未在繁中 Agent 考卷上實測。',
    kvPerTokKB: 48,
    speedPrefillScore: 84,
    speedDecodeRating: '未實測（啟用 17.0B）',
    workloadFit: { prefill: 3.8, decode: 4.0, agent: 3.9 },
    engineSupport: 'Production Merged',
    engineNotes: 'vLLM、llama.cpp 正式支援。',
    storageAdvise: 'Q4 約 65 GB。',
    examScore: null,
    isDay16Featured: false,
    day16Role: '超長上下文（10M）MoE',
    editorial: 'workloadFit、speedPrefillScore 依規則產生（架構與啟用參數量）；tcGrade 未評',
    quantProfiles: {
      BF16: { sizeGB: 217.3, bpw: 16.0, recSpeedGpu: '256 GB 以上' },
      Q8_0: { sizeGB: 114.5, bpw: 8.4, recSpeedGpu: '128 GB 邊緣' },
      Q4_K_M: { sizeGB: 65.4, bpw: 4.8, recSpeedGpu: '96 GB' }
    },
    sources: {
      arena: 'https://arena.ai/leaderboard/text/coding',
      specs: 'https://huggingface.co/meta-llama/Llama-4-Scout-17B-16E-Instruct',
      benchmarks: 'https://huggingface.co/meta-llama/Llama-4-Scout-17B-16E-Instruct（LiveCodeBench）',
      quant: 'https://huggingface.co/unsloth/Llama-4-Scout-17B-16E-Instruct-GGUF'
    }
  },
  {
    id: 'glm-53-flash',
    name: 'GLM-5.3-Flash (MoE 320B / Active 18B)',
    family: 'GLM',
    paramsTotal: 320.0,
    paramsActive: 18.0,
    architecture: 'MoE',
    license: 'MIT',
    commercialAllowed: true,
    contextWindow: 1048576,
    nativeContext: 1048576,
    arenaKey: 'glm-5.3-flash',
    arenaWebdevKey: 'glm-5.3-flash',
    arenaCodeElo: 1525.1,
    arenaWebdevElo: 1607.1,
    humanEval: null,
    sweBench: null,
    liveCodeBench: null,
    tcGrade: '未評',
    tcQuantMinBit: '8-bit 起步（繁中通則）',
    tcQuantNote: '34 層 KDA 線性注意力加 11 層 MLA 稀疏注意力，KV 成本很低；程式碼評測只有圖片。',
    jsonDisciplineScore: null,
    jsonNote: '未在繁中 Agent 考卷上實測。',
    kvPerTokKB: 11,
    speedPrefillScore: 84,
    speedDecodeRating: '未實測（啟用 18.0B）',
    workloadFit: { prefill: 3.8, decode: 4.0, agent: 3.9 },
    engineSupport: 'Production Merged',
    engineNotes: 'unsloth 已發布 GGUF。',
    storageAdvise: 'UD-Q4_K_XL 約 200 GB，需 256GB 以上。',
    examScore: null,
    isDay16Featured: false,
    day16Role: '開放權重 coding 榜前段的 MIT 授權 MoE',
    editorial: 'workloadFit、speedPrefillScore 依規則產生（架構與啟用參數量）；tcGrade 未評',
    quantProfiles: {
      Q8_0: { sizeGB: 341.0, bpw: 8.5, recSpeedGpu: '512 GB' },
      'UD-Q4_K_XL': { sizeGB: 199.7, bpw: 5.0, recSpeedGpu: '256 GB' }
    },
    sources: {
      arena: 'https://arena.ai/leaderboard/text/coding；https://arena.ai/leaderboard/code/webdev',
      specs: 'https://huggingface.co/zai-org/GLM-5.3-Flash',
      quant: 'https://huggingface.co/unsloth/GLM-5.3-Flash-GGUF'
    }
  },
  {
    id: 'kimi-k3',
    name: 'Kimi-K3 (MoE 2.8T / Active 104B)',
    family: 'Kimi',
    paramsTotal: 2800.0,
    paramsActive: 104.0,
    architecture: 'MoE',
    license: 'Kimi K3 License',
    commercialAllowed: false,
    contextWindow: 1048576,
    nativeContext: 1048576,
    arenaKey: 'kimi-k3-max',
    arenaWebdevKey: 'kimi-k3-max',
    arenaCodeElo: 1538.4,
    arenaWebdevElo: 1674.3,
    humanEval: null,
    sweBench: null,
    liveCodeBench: null,
    tcGrade: '未評',
    tcQuantMinBit: '8-bit 起步（繁中通則）',
    tcQuantNote: 'MXFP4 QAT 權重；授權為自訂條款，商用前要讀。',
    jsonDisciplineScore: null,
    jsonNote: '未在繁中 Agent 考卷上實測。',
    kvPerTokKB: 27,
    speedPrefillScore: 84,
    speedDecodeRating: '未實測（啟用 104.0B）',
    workloadFit: { prefill: 3.8, decode: 3.0, agent: 3.4 },
    engineSupport: 'Production Merged',
    engineNotes: 'unsloth 已發布 GGUF。',
    storageAdvise: '約 1.5 TB，資料中心等級。',
    examScore: null,
    isDay16Featured: false,
    day16Role: '開放權重 coding 榜第一名，本地部署門檻極高',
    editorial: 'workloadFit、speedPrefillScore 依規則產生（架構與啟用參數量）；tcGrade 未評',
    quantProfiles: {
      MXFP4: { sizeGB: 1560.9, bpw: 4.5, recSpeedGpu: '多卡資料中心' },
      'UD-Q4_K_XL': { sizeGB: 1508.7, bpw: 4.3, recSpeedGpu: '多卡資料中心' }
    },
    sources: {
      arena: 'https://arena.ai/leaderboard/text/coding；https://arena.ai/leaderboard/code/webdev',
      specs: 'https://huggingface.co/moonshotai/Kimi-K3',
      quant: 'https://huggingface.co/unsloth/Kimi-K3-GGUF'
    }
  },
  {
    id: 'minimax-m3',
    name: 'MiniMax-M3 (MoE 428B / Active 23B)',
    family: 'MiniMax',
    paramsTotal: 428.0,
    paramsActive: 23.0,
    architecture: 'MoE',
    license: 'MiniMax Community License',
    commercialAllowed: false,
    contextWindow: 1048576,
    nativeContext: 1048576,
    arenaKey: 'minimax-m3',
    arenaWebdevKey: 'minimax-m3',
    arenaCodeElo: 1496.3,
    arenaWebdevElo: 1486.7,
    humanEval: null,
    sweBench: null,
    liveCodeBench: null,
    tcGrade: '未評',
    tcQuantMinBit: '8-bit 起步（繁中通則）',
    tcQuantNote: 'GQA 加 MSA 區塊稀疏，稀疏只省運算不省 KV。',
    jsonDisciplineScore: null,
    jsonNote: '未在繁中 Agent 考卷上實測。',
    kvPerTokKB: 120,
    speedPrefillScore: 84,
    speedDecodeRating: '未實測（啟用 23.0B）',
    workloadFit: { prefill: 3.8, decode: 3.5, agent: 3.6 },
    engineSupport: 'Production Merged',
    engineNotes: 'unsloth 已發布 GGUF。',
    storageAdvise: 'Q4 約 264 GB，需 512GB 等級。',
    examScore: null,
    isDay16Featured: false,
    day16Role: '大型 MoE，授權為社群條款',
    editorial: 'workloadFit、speedPrefillScore 依規則產生（架構與啟用參數量）；tcGrade 未評',
    quantProfiles: {
      Q8_0: { sizeGB: 452.7, bpw: 8.5, recSpeedGpu: '512 GB 邊緣' },
      Q4_K_M: { sizeGB: 264.0, bpw: 4.9, recSpeedGpu: '512 GB' }
    },
    sources: {
      arena: 'https://arena.ai/leaderboard/text/coding；https://arena.ai/leaderboard/code/webdev',
      specs: 'https://huggingface.co/MiniMaxAI/MiniMax-M3',
      quant: 'https://huggingface.co/unsloth/MiniMax-M3-GGUF'
    }
  },
  {
    id: 'nemotron-3-super',
    name: 'NVIDIA-Nemotron-3-Super-120B-A12B (MoE 120B / Active 12B)',
    family: 'Nemotron',
    paramsTotal: 123.6,
    paramsActive: 12.0,
    architecture: 'MoE',
    license: 'NVIDIA Nemotron Open Model License (允許商用)',
    commercialAllowed: true,
    contextWindow: 1048576,
    nativeContext: 262144,
    arenaKey: 'nvidia-nemotron-3-super-120b-a12b',
    arenaWebdevKey: null,
    arenaCodeElo: 1408.3,
    arenaWebdevElo: null,
    humanEval: null,
    sweBench: null,
    liveCodeBench: 81.2,
    tcGrade: '未評',
    tcQuantMinBit: '8-bit 起步（繁中通則）',
    tcQuantNote: 'Mamba-2 與 LatentMoE 交錯，88 層只有 8 層是注意力層，所以 KV 很小（Mamba 狀態為定量）。官方支援語言含中文。LiveCodeBench 為 v5（2024-07~12）；官方 SWE-Bench（OpenHands）60.47，但未註明是 Verified，這裡不填。',
    jsonDisciplineScore: null,
    jsonNote: '第三方 Exxact OpenClaw agent 基準（2026-05-14，DGX Spark）：工具呼叫 17/17、多步鏈深 6 跳，是該次最完整的 agent 表現；同測 Qwen3.5-35B-A3B 為 17/17、4 跳。未在繁中 Agent 考卷上實測。',
    kvPerTokKB: 8,
    speedPrefillScore: 84,
    speedDecodeRating: '16.4 t/s（第三方 Exxact DGX Spark 實測）',
    workloadFit: { prefill: 3.8, decode: 4.0, agent: 3.9 },
    engineSupport: 'Production Merged',
    engineNotes: '官方提供 vLLM 與 SGLang 啟動方式；unsloth 已發布 GGUF。預設上下文 256K，開到 1M 要另設參數。',
    storageAdvise: '官方 NVFP4 約 80 GB，128GB 機器可放並留共存餘裕。',
    examScore: null,
    isDay16Featured: false,
    day16Role: '128GB 等級工具呼叫最完整的第三方實測代表：多步鏈深，但 decode 偏慢',
    editorial: 'workloadFit、speedPrefillScore 依規則產生（架構與啟用參數量）；tcGrade 未評',
    quantProfiles: {
      BF16: { sizeGB: 247.2, bpw: 16.0, recSpeedGpu: '256 GB 以上' },
      FP8: { sizeGB: 128.4, bpw: 8.3, recSpeedGpu: '雙機 GB10 / 192 GB 以上' },
      NVFP4: { sizeGB: 80.3, bpw: 5.2, recSpeedGpu: '16.4 t/s（第三方 Exxact DGX Spark 實測）' },
      Q8_0: { sizeGB: 128.5, bpw: 8.3, recSpeedGpu: '192 GB 以上' },
      'UD-Q4_K_M': { sizeGB: 82.5, bpw: 5.3, recSpeedGpu: '96~128 GB' }
    },
    sources: {
      arena: 'https://arena.ai/leaderboard/text/coding',
      specs: 'https://huggingface.co/nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-BF16',
      benchmarks: 'https://huggingface.co/nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-BF16（LiveCodeBench v5）',
      quant: 'https://huggingface.co/unsloth/NVIDIA-Nemotron-3-Super-120B-A12B-GGUF',
      local: 'https://www.exxactcorp.com/blog/benchmarks/benchmarking-local-ai-agents-on-nvidia-dgx-spark（第三方）'
    }
  }
];

const DAY16_METHODOLOGY = {
  title: 'Day 16｜模型選型方法論：五個問題幫你跳脫排行榜迷失，找到適合自己任務用的 AI 模型',
  articleUrl: 'https://ithelp.ithome.com.tw/articles/10405898',
  examRepo: 'https://github.com/ivanusto/llm-zhtw-agent-exam',
  threeMyths: [
    {
      id: 1,
      title: '排行榜量的語言不是你的語言',
      icon: 'globe',
      summary: '量化對繁中的傷害是英文的 1.6 到 2 倍！跨引擎跨量化家族都成立。英文榜上的名次到了繁中任務會重新洗牌。',
      quote: '英文社群說「4-bit 無感」時，他們沒有替你驗過。'
    },
    {
      id: 2,
      title: '排行榜不量你的工作負載形狀',
      icon: 'activity',
      summary: '同一款密集 27B，prefill 對 decode 的效率差了 200 倍。做長文摘要是神器，拿來寫長文是折磨。榜上只有一個分數。',
      quote: '看啟用參數量，不是總參數量。'
    },
    {
      id: 3,
      title: '排行榜不量禮儀與格式紀律',
      icon: 'check-square',
      summary: '五個配方在能力題全數滿分，卻在「只輸出一個 JSON 不要多話」這題拉出 0/50 到 40/50 的差距！agent 迴圈一天幾百輪，直接決定帳單。',
      quote: '願不願意當白老鼠是個人選擇，把白老鼠環境放進生產服務是專業錯誤。'
    }
  ],
  storageRules: [
    {
      question: '它放得進記憶體嗎？',
      yesAction: '放得進：NAS 的代價只是冷啟動多十幾秒的一次性成本。',
      noAction: '放不進：絕不要放 NAS！每一次頁面回收再讀取都走網路，最慘案例總載入慢 3.8 倍！'
    },
    {
      question: '你的 loader 吃儲存速度嗎？',
      yesAction: '同數量級（如 GGUF mmap 達 73%）：儲存速度直接反映在啟動時間，住本機 NVMe。',
      noAction: '差一個數量級（如 vLLM 僅 3%）：搬去快碟不會有感。'
    }
  ],
  onePageRules: [
    { num: 1, topic: '任務形狀', rule: '長進短出選密集，短進長出選 MoE（看啟用量），agent 全都要看' },
    { num: 2, topic: '繁體中文', rule: '8-bit 起步、imatrix 優先、自己的語料自己驗' },
    { num: 3, topic: '記憶體', rule: '先決定獨佔還是共存，再看權重加 KV 加餘裕' },
    { num: 4, topic: '授權', rule: 'MANIFEST 裡那行 license 就是答案（商用認明 Apache/MIT）' },
    { num: 5, topic: '生態', rule: '支援沒合併的是實驗品，實驗品不進生產' }
  ]
};

// Export to window for global browser usage
if (typeof window !== 'undefined') {
  window.HARDWARE_PROFILES = HARDWARE_PROFILES;
  window.MODELS_DATABASE = MODELS_DATABASE;
  window.DAY16_METHODOLOGY = DAY16_METHODOLOGY;
  window.DATA_ASOF = DATA_ASOF;
}
